### ISSUE TITLE
The overlay does not go away

### ISSUE THREAD

**Issue by hoseja** [p3t3rix-vsmods/VsProspectorInfo#2]
First it worked well, only showing when holding the propick. Then (I think) I took the pick out of my hotbar while it was in the active slot and since then the overlay stays on, no matter what I do. Using the latest version.

**Comment by p3t3rix** [comment]
Ok it should go away after switching from a slot with a prospecting pick to a normal slot. Also make sure you didn't accidentally activate the "pi showoverlay" aka. RenderTexturesOnMap configoption (this will always render it).
Still this a bug. Will fix it soon.

**Comment by p3t3rix** [comment]
fixed with release 3.1
