### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by Mirosana** [p3t3rix-vsmods/VsProspectorInfo#20]
Mod was working perfecly fine then the next day it just started to crash my game whenever I load up a world.

**Comment by GGGuenni** [comment]
Please add a crash log
We can not do anything without more info

**Comment by danzio** [comment]
I have same problem, attaching crash log here. Crash is happening when I changed world properties to enable node detection - before that I could prospect just fine (with HUD on map).
[client-crash.txt](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/10502374/client-crash.txt)

**Comment by p3t3rix** [comment]
Does the crash happen on startup with the new wold properties or just when you use the pick ? Does deactivating the mod fix the crash ?

**Comment by danzio** [comment]
Crashes happen on startup, previously I did some prospecting before changing properties (and prospected chunks showed on map just fine).
Deactivating mod fixes crash, so I continued playing without mod.
Never tried activating mod and checking with new save (and enabling node detection on worldgen) - I will check this later today and make you know about issues.

**Comment by p3t3rix** [comment]
Closed for inactivity. Feel free to reopen if the issue persists.
