### ISSUE TITLE
[FR] Allow the sharing of this data with other people in multiplayer

### ISSUE THREAD

**Issue by FalcoGer** [p3t3rix-vsmods/VsProspectorInfo#21]
It would be great if the data could be shared in multiplayer between players, maybe even automatically updated when someone prospected an area.

I made something that can be used for this, but it's manual and offline only.

https://github.com/FalcoGer/VSProspectorInfoMerger

**Comment by p3t3rix** [comment]
As i am no longer playing this game i won't have time to implement such a feature, but it should be quite easy to implement some chat command to import or export data (could be zipped and base64 encoded for example). This data would of course only be useful for the same world. 
Automatically updating could also be done although i would like this mod to stay client only (so chat could be a way to transmit this data although probably a noisy one, not sure about other ways a client can do client2client communication). 
If you feel up to the task you can create a PR.
Maybe @GGGuenni has also some ideas.

**Comment by FalcoGer** [comment]
I am decently well versed with C# as a language, but I have never written a code mod for VS before. Maybe someone else who thinks this would be nice and is better at mod making than me could do this.

**Comment by GGGuenni** [comment]
Since this mod should be kept client only and I don't want to fiddle around with sending data over chat I'm not going to implement it sorry.

But if your familiar with c# you can definitely try to do it if you've got the time👌 It's always good to work on open source stuff to improve your coding skills!

**Comment by p3t3rix** [comment]
Since this issue is not picked up by anyone of us, i will close this for now. If anyone wants to pick this up feel free to reopen and/or submit a pull-request.
