### ISSUE TITLE
Appears to crash on world load in 1.18.0.rc-pre7

### ISSUE THREAD

**Issue by OpPointBaker** [p3t3rix-vsmods/VsProspectorInfo#28]
Just updated to pre 7 and upon loading into a world, the game CTD's
[client-crash.txt](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/11009971/client-crash.txt)

**Comment by Wooza** [comment]
I uploaded a work in progress version that should work with 1.18.0-pre7 in #23. Feel free to try it.

**Comment by p3t3rix** [comment]
Should work with version 4.2.0 and game version 1.8.0 upwards, if not please open another ticket
