### ISSUE TITLE
Error when loading prospectorinfo in VS version 1.16.0

### ISSUE THREAD

**Issue by Stampede602** [p3t3rix-vsmods/VsProspectorInfo#3]
I'm seeing the following error in the client logs when trying to load prospectorinfo 3.1.2 on VS version 1.16.0

19.1.2022 18:06:25 [Error] [prospectorinfo] An exception was thrown when trying to start the mod:
System.MissingMethodException: Method not found: '!!0 Vintagestory.API.Common.IModLoader.GetModSystem()'.
   at ProspectorInfo.ProspectorInfoModSystem.StartClientSide(ICoreClientAPI api)
   at Vintagestory.Common.ModLoader.TryStartSystem(Mod mod, ModSystem system, ICoreAPI api, ModEventPhase phase)
19.1.2022 18:06:25 [Error] Failed to start system ProspectorInfo.ProspectorInfoModSystem

**Comment by p3t3rix** [comment]
Do you have other mods installed ? Did you try it in a new world ?
I just tried it with the 1.16,0 version and it worked for me 🤔

**Comment by Stampede602** [comment]
prospector info is the only mod currently installed. It was a fresh world generated in 1.16.0. I have tried this is single and multiplayer. I previously had VSProspectoInfo installed. If it's working for you I'll try reinstalling VS.

**Comment by Stampede602** [comment]
Same error message after uninstalling VS and clearing out the appdata folder. I re-installed and created a new world. Logs attached if they help.
[VSLogs.zip](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/7903724/VSLogs.zip)
d

**Comment by p3t3rix** [comment]
Can you send me the zip of the mod ?

**Comment by Stampede602** [comment]
[ProspectorInfo-3.1.2.zip](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/7910396/ProspectorInfo-3.1.2.zip)
Here is the version I downloaded from ModDB.

**Comment by p3t3rix** [comment]
Hmm, also works for me. Which version of .Net framework do you have installed ? Tyron told me it could be related to it.

**Comment by Stampede602** [comment]
.Net framework version 4.8.04084 according to my registry

**Comment by tyronx** [comment]
I'd recommend uninstalling and reinstalling the .net framework

**Comment by p3t3rix** [comment]
@Stampede602 Do you have the mod unzipped or lying around in more than one folder ? For example in the game install mods folder and the appdata one ?

**Comment by Stampede602** [comment]
The issue appears to be resolved after updating VS to version 1.16.1. Though at some point in the last 12 hours a copy of the .dll and modinfo.json did get copied to the install folder. Possibly during the upgrade?? I know they weren't there before yesterday. After clearing the mod out of the install folder the mod loaded correctly.

Before upgrading VS I did try using Microsoft's .net framework repair tool which didn't seem to have any effect after making some changes to my registry.

Thank you both for troubleshooting! I know it's not something you have to spend your time doing and I appreciate your time and effort!
