### ISSUE TITLE
Currently incompatible with Vintage Story 1.17

### ISSUE THREAD

**Issue by Ginko72** [p3t3rix-vsmods/VsProspectorInfo#5]
The title says it all.  😄 

This is one of my must have mods so I look forward to it being updated.

**Comment by p3t3rix** [comment]
Not sure what you mean the current release 3.1.2 works with the current 1.17.0-pre.3. Is there something that does not work ? some specific error you experience ?

**Comment by p3t3rix** [comment]
Please try the new version 3.2.0, which is compiled against 1.17 pre3.
If you still having issues, please re-open and elaborate further what part isn't working and steps to reproduce.
